name: About The Fish
favicon: null
layout_spectrum: 0.09570466983132064
typography_spectrum: 0.6361428964883089
title: About The Fish
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#5d921c'
    - '#d2e5f6'
    - '#b9d7f1'
    - '#95c2eb'
  brandStrength: 0.6109916360583156
  lightness: 0.0934388735331595
  saturation: 0.7031587425153702
  rhythmicContrast: 0.9196887712460011
purpose: []
